### ISSUE TITLE
Error at Step 4: Calculate minima

### ISSUE THREAD

**Issue by Sohambiswas8** [endrebak/ldetect#3]
Hi, 

I plan to use ldetect for my population genotype data rather than the available 1000 Genomes population data. So, first I was trying to replicate the work done here. I used the same Chr2 VCF from the FTP link given and used the respective genetic map. The individual panel is same. For the same reason, I am only using SNPs from 39967768-40067768 as the example here. Yet, I am getting error during Step 4. 

```
Run parameters: P02_minima_pipeline.py --input_fname=example_data/vector/vector-EUR-chr2-39967768-40067768.txt.gz --chr_name=chr2 --dataset_path=example_data/cov_matrix/ --n_snps_bw_bpoints=50 --out_fname=example_data/minima/minima-EUR-chr2-50-39967768-40067768.pickle
[20:44:10] * Reading data
[20:44:10] * Number of breakpoints: 13
[20:44:10] * Starting search...
[20:44:10] Starting custom_binary_search_with_trackback
Traceback (most recent call last):
  File "/home/hp/env/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2344, in get_window
    beta = float(window)
ValueError: could not convert string to float: 'hanning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/env/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2362, in get_window
    winfunc = _win_equiv[winstr]
KeyError: 'hanning'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/hp/UbuntuDrive/1KGPh1/ldetect/examples/P02_minima_pipeline.py", line 233, in <module>
    cl.commander_line((pipeline))
  File "/home/hp/env/lib/python3.10/site-packages/commanderline/commander_line.py", line 366, in commander_line
    return_value = func(**unwrap_options)
  File "/media/hp/UbuntuDrive/1KGPh1/ldetect/examples/P02_minima_pipeline.py", line 51, in pipeline
    found_width = find_minima.custom_binary_search_with_trackback(np_init_array, filt.apply_filter_get_minima, n_bpoints, trackback_delta=trackback_delta, trackback_step=trackback_step, init_search_location=init_search_location)
  File "/home/hp/env/lib/python3.10/site-packages/ldetect/pipeline_elements/E05_find_minima.py", line 102, in custom_binary_search_with_trackback
    end_v = find_end(np_init_array, f, init_search_location, srch_val)
  File "/home/hp/env/lib/python3.10/site-packages/ldetect/pipeline_elements/E05_find_minima.py", line 60, in find_end
    if f(data, x) < val:
  File "/home/hp/env/lib/python3.10/site-packages/ldetect/baselib/filters.py", line 6, in apply_filter_get_minima
    el = apply_filter(np_init_array, width)
  File "/home/hp/env/lib/python3.10/site-packages/ldetect/baselib/filters.py", line 27, in apply_filter
    a=sig.get_window('hanning',2*width+1)
  File "/home/hp/env/lib/python3.10/site-packages/scipy/signal/windows/_windows.py", line 2364, in get_window
    raise ValueError("Unknown window type.") from e
ValueError: Unknown window type.
```
If the previous covariance matrix and vector files are the same as they should be, then I am unable to understand why such an error is occurring. I would be highly grateful if you kindly look into it. 

Thank you

**Comment by Haleyeye** [comment]
Hi, I got same issue, have you find any solution?

**Comment by Sohambiswas8** [comment]
> Hi, I got same issue, have you find any solution?

Hi, @Haleyeye, sorry for a late reply. I solved it. 

change the line in ```ldetect/baselib/filters.py``` from ``` a = sig.get_window('hanning', 2 * width + 1) ``` to ``` a = sig.get_window('hann', 2 * width + 1) ```. The 'hanning' alias was deprecated in later versions of SciPy. That's why the bug. 

Thanks,
Soham
